# -----------------------------------------------------------------------------------------------
# This workflow built the project on every pull request and on every manual trigger.
# This workflow is used in pull request as a required check.
# -----------------------------------------------------------------------------------------------
name: "CI - Build & Test"
run-name: CI - Run maven Build & Test

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  MVNW: ${{ github.workspace }}/mvnw

permissions:
  contents: read
  pull-requests: write
  checks: write
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Documentation: https://github.com/actions/checkout
      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: "Setup Java"
        id: setup-java
        uses: alderichoarau/gha-setup-java@v2
        with:
          java-version: "25"
          distribution: temurin

      - name: "Build with Maven"
        if: steps.setup-java.outcome == 'success'
        run: |
          ${MVNW} -B clean package
